api_demos:
    path:     /demos
    defaults: { _controller: AppBackEndBundle:Demos:index }
    methods: [GET]

api_demos_get:
    path:     /demos/{id}
    defaults: { _controller: AppBackEndBundle:Demos:get }
    methods: [GET]

api_demos_post:
    path:     /demos
    defaults: { _controller: AppBackEndBundle:Demos:post }
    methods: [POST]

api_demos_put:
    path:     /demos/{id}
    defaults: { _controller: AppBackEndBundle:Demos:put }
    methods: [PUT]

api_demos_delete:
    path:     /demos/{id}
    defaults: { _controller: AppBackEndBundle:Demos:delete }
    methods: [DELETE]
